//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleExternalMedia
    {
        public int ID { get; set; }
        public Nullable<int> ArticleExternalLinkID { get; set; }
        public Nullable<int> ArticleExternalMediaTypeID { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
    
        public virtual ArticleExternalLinks ArticleExternalLinks { get; set; }
        public virtual ArticleExternalMediaType ArticleExternalMediaType { get; set; }
    }
}
