//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInfo
    {
        public int ID { get; set; }
        public Nullable<long> MemberID { get; set; }
        public string First_Name { get; set; }
        public string Middle_Initial { get; set; }
        public string Last_Name { get; set; }
        public Nullable<int> Billing_Country_Code { get; set; }
        public string Billing_Address_Line_1 { get; set; }
        public string Billing_Address_Line_2 { get; set; }
        public string Billing_City { get; set; }
        public string Billing_State_Abrv { get; set; }
        public string Billing_Zip { get; set; }
        public Nullable<int> CC_TypeID { get; set; }
        public string CC_NameOnCard { get; set; }
        public string CC_Number { get; set; }
        public string CC_expire_month { get; set; }
        public string CC_expire_year { get; set; }
        public string CC_cvv2 { get; set; }
    
        public virtual CCType CCType { get; set; }
        public virtual CountryCodes CountryCodes { get; set; }
        public virtual Member Member { get; set; }
    }
}
