//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogEntries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogEntries()
        {
            this.BlogEntryComments = new HashSet<BlogEntryComments>();
            this.BlogEntryFiles = new HashSet<BlogEntryFiles>();
            this.BlogEntryPingbacks = new HashSet<BlogEntryPingbacks>();
            this.Tags = new HashSet<Tags>();
        }
    
        public System.Guid Id { get; set; }
        public string Header { get; set; }
        public string HeaderUrl { get; set; }
        public string Author { get; set; }
        public string ShortContent { get; set; }
        public string Content { get; set; }
        public int Visits { get; set; }
        public bool Visible { get; set; }
        public System.DateTime PublishDate { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogEntryComments> BlogEntryComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogEntryFiles> BlogEntryFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogEntryPingbacks> BlogEntryPingbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tags> Tags { get; set; }
    }
}
