//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDSEvent
    {
        public CDSEvent()
        {
            this.EventMedias = new HashSet<EventMedia>();
        }
    
        public int eventID { get; set; }
        public string title { get; set; }
        public long createdBy { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateEnd { get; set; }
        public int eventTypeID { get; set; }
        public Nullable<int> groupID { get; set; }
        public System.DateTime createdOn { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<int> doubleDateRequestID { get; set; }
        public string description { get; set; }
        public Nullable<int> eventStatusID { get; set; }
    
        public virtual DoubleDateRequest DoubleDateRequest { get; set; }
        public virtual EventStatus EventStatu { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<EventMedia> EventMedias { get; set; }
    }
}
