//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<C__MigrationHistoryBkup> C__MigrationHistoryBkup { get; set; }
        public virtual DbSet<AddressInfo> AddressInfo { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<ArticleExternalLinks> ArticleExternalLinks { get; set; }
        public virtual DbSet<ArticleExternalMedia> ArticleExternalMedia { get; set; }
        public virtual DbSet<ArticleExternalMediaType> ArticleExternalMediaType { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Attributes> Attributes { get; set; }
        public virtual DbSet<BillingInfo> BillingInfo { get; set; }
        public virtual DbSet<BlogEntries> BlogEntries { get; set; }
        public virtual DbSet<BlogEntryComments> BlogEntryComments { get; set; }
        public virtual DbSet<BlogEntryFiles> BlogEntryFiles { get; set; }
        public virtual DbSet<BlogEntryPingbacks> BlogEntryPingbacks { get; set; }
        public virtual DbSet<CountryCodes> CountryCodes { get; set; }
        public virtual DbSet<DoubleDateDetails> DoubleDateDetails { get; set; }
        public virtual DbSet<DoubleDateMediaUploads> DoubleDateMediaUploads { get; set; }
        public virtual DbSet<DoubleDateRequest> DoubleDateRequest { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventMedia> EventMedia { get; set; }
        public virtual DbSet<EventStatus> EventStatus { get; set; }
        public virtual DbSet<EventType> EventType { get; set; }
        public virtual DbSet<FavoritePlaces> FavoritePlaces { get; set; }
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<FeedStatistics> FeedStatistics { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Interest> Interest { get; set; }
        public virtual DbSet<MediaType> MediaType { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberAttributes> MemberAttributes { get; set; }
        public virtual DbSet<MemberInterest> MemberInterest { get; set; }
        public virtual DbSet<MemberMedia> MemberMedia { get; set; }
        public virtual DbSet<MembershipPackage> MembershipPackage { get; set; }
        public virtual DbSet<MembershipPayments> MembershipPayments { get; set; }
        public virtual DbSet<Memberships> Memberships { get; set; }
        public virtual DbSet<MemberStatus> MemberStatus { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<OptIn> OptIn { get; set; }
        public virtual DbSet<OptInQAnswers> OptInQAnswers { get; set; }
        public virtual DbSet<PaymentStatus> PaymentStatus { get; set; }
        public virtual DbSet<PaymentType> PaymentType { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<PlaceLinks> PlaceLinks { get; set; }
        public virtual DbSet<PlaceLinkType> PlaceLinkType { get; set; }
        public virtual DbSet<PlaceMedia> PlaceMedia { get; set; }
        public virtual DbSet<PlaceTags> PlaceTags { get; set; }
        public virtual DbSet<PlaceType> PlaceType { get; set; }
        public virtual DbSet<PlaceTypes> PlaceTypes { get; set; }
        public virtual DbSet<ProfileQuestionAnswers> ProfileQuestionAnswers { get; set; }
        public virtual DbSet<ProfileQuestions> ProfileQuestions { get; set; }
        public virtual DbSet<QuestionAnswers> QuestionAnswers { get; set; }
        public virtual DbSet<QuestionCategory> QuestionCategory { get; set; }
        public virtual DbSet<QuestionChoices> QuestionChoices { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<SubQuestions> SubQuestions { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<TagType> TagType { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<UserProfileAnswers> UserProfileAnswers { get; set; }
        public virtual DbSet<ZipcodeCalculations> ZipcodeCalculations { get; set; }
        public virtual DbSet<CCType> CCType { get; set; }
        public virtual DbSet<PaymentPlans> PaymentPlans { get; set; }
        public virtual DbSet<EventRegistration> EventRegistration { get; set; }
        public virtual DbSet<vwChoices> vwChoices { get; set; }
        public virtual DbSet<vwQuestionAnswers> vwQuestionAnswers { get; set; }
    
        public virtual int spMatch(Nullable<long> member1)
        {
            var member1Parameter = member1.HasValue ?
                new ObjectParameter("member1", member1) :
                new ObjectParameter("member1", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spMatch", member1Parameter);
        }
    
        public virtual int spMatchMembers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spMatchMembers");
        }
    
        public virtual int DeleteUserByEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUserByEmail", emailParameter);
        }
    
        public virtual int DeleteUsersWithNullUserIDs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUsersWithNullUserIDs");
        }
    }
}
