//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoubleDateRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoubleDateRequest()
        {
            this.DoubleDateDetails = new HashSet<DoubleDateDetails>();
            this.DoubleDateMediaUploads = new HashSet<DoubleDateMediaUploads>();
        }
    
        public int ID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public long RequestingMemberID { get; set; }
        public long RequestToMemberID { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> RequestedDateMeetTime { get; set; }
        public string RequestingMemberReview { get; set; }
        public string RequestedMemberReview { get; set; }
        public Nullable<int> RequestingMemberRating { get; set; }
        public Nullable<int> RequestedMemberRating { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoubleDateDetails> DoubleDateDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoubleDateMediaUploads> DoubleDateMediaUploads { get; set; }
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
