//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoubleDateMediaUploads
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Memo { get; set; }
        public string Path { get; set; }
        public Nullable<int> DoubleDateRequestID { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<long> MemberID { get; set; }
    
        public virtual DoubleDateRequest DoubleDateRequest { get; set; }
        public virtual Place Place { get; set; }
        public virtual Member Member { get; set; }
    }
}
