//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoubleDateDetails
    {
        public int ID { get; set; }
        public int DoubleDateRequestID { get; set; }
        public short PlaceSequenceNbr { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public string gPlaceID { get; set; }
        public Nullable<System.TimeSpan> MeetTime { get; set; }
        public string ExternalPlaceName { get; set; }
        public string ExternalPlaceAddress { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual DoubleDateRequest DoubleDateRequest { get; set; }
    }
}
