//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMedia
    {
        public int ID { get; set; }
        public int EventID { get; set; }
        public string Path { get; set; }
        public Nullable<int> MediaTypeID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Name { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual MediaType MediaType { get; set; }
    }
}
