//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRegistration
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<long> MemberID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public Nullable<bool> Canceled { get; set; }
        public Nullable<System.DateTime> DateCanceled { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Member Member { get; set; }
    }
}
