//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int groupID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime createdOn { get; set; }
        public long createdBy { get; set; }
    }
}
