//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberInterest
    {
        public int ID { get; set; }
        public Nullable<int> InterestID { get; set; }
        public Nullable<long> MemberID { get; set; }
    
        public virtual Interest Interest { get; set; }
        public virtual Member Member { get; set; }
    }
}
