//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memberships
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Memberships()
        {
            this.MembershipPayments = new HashSet<MembershipPayments>();
        }
    
        public int membershipID { get; set; }
        public Nullable<long> memberId { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<System.DateTime> canceledDate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> effectiveDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> paymentPlanID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembershipPayments> MembershipPayments { get; set; }
        public virtual PaymentPlans PaymentPlans { get; set; }
    }
}
