//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipPayments
    {
        public long PaymentID { get; set; }
        public Nullable<int> membershipID { get; set; }
        public Nullable<int> paymentTypeID { get; set; }
        public Nullable<decimal> paymentAmount { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> paymentStatusID { get; set; }
        public string token { get; set; }
        public Nullable<int> CCInfoID { get; set; }
        public Nullable<int> BillingInfoID { get; set; }
        public string PayPal_UserName { get; set; }
    
        public virtual PaymentStatus PaymentStatus { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual Memberships Memberships { get; set; }
    }
}
