//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int ID { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public long memberID { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<int> replyMessageID { get; set; }
        public Nullable<long> toMemberID { get; set; }
        public Nullable<bool> isRead { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
