//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentPlans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentPlans()
        {
            this.Memberships = new HashSet<Memberships>();
        }
    
        public int PaymentPlanID { get; set; }
        public int PackageID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isRecurring { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
    
        public virtual MembershipPackage MembershipPackage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Memberships> Memberships { get; set; }
    }
}
