//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceTypes
    {
        public int PlaceTypesID { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<int> PlaceTypeID { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual PlaceType PlaceType { get; set; }
    }
}
