//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceMedia
    {
        public int PlaceMediaID { get; set; }
        public int MediaTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public string path { get; set; }
    
        public virtual Place Place { get; set; }
    }
}
