//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questions()
        {
            this.QuestionChoices = new HashSet<QuestionChoices>();
            this.SubQuestions = new HashSet<SubQuestions>();
            this.SubQuestions1 = new HashSet<SubQuestions>();
        }
    
        public int questionID { get; set; }
        public string questionName { get; set; }
        public string questionFull { get; set; }
        public Nullable<short> questionCategoryID { get; set; }
        public Nullable<short> questionImportance { get; set; }
        public Nullable<bool> multipleAnswersAllowed { get; set; }
        public Nullable<bool> enabled { get; set; }
    
        public virtual QuestionCategory QuestionCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionChoices> QuestionChoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubQuestions> SubQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubQuestions> SubQuestions1 { get; set; }
    }
}
