//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubQuestions
    {
        public int subquestionID { get; set; }
        public Nullable<int> parentQuestionID { get; set; }
        public Nullable<int> childQuestionID { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Questions Questions1 { get; set; }
    }
}
