//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMember
    {
        public tblMember()
        {
            this.tblMemberAttributes = new HashSet<tblMemberAttributes>();
            this.tblQuestionAnswers = new HashSet<tblQuestionAnswers>();
            this.tblMemberMedia = new HashSet<tblMemberMedia>();
            this.Messages = new HashSet<Messages>();
            this.Friends = new HashSet<Friends>();
            this.Friends1 = new HashSet<Friends>();
            this.Favorites = new HashSet<Favorites>();
            this.Favorites1 = new HashSet<Favorites>();
            this.DoubleDateMediaUploads = new HashSet<DoubleDateMediaUploads>();
            this.DoubleDateRequest = new HashSet<DoubleDateRequest>();
            this.DoubleDateRequest1 = new HashSet<DoubleDateRequest>();
            this.FavoritePlaces = new HashSet<FavoritePlaces>();
            this.MemberInterest = new HashSet<MemberInterest>();
            this.tblMemberships = new HashSet<tblMemberships>();
        }
    
        public long memberId { get; set; }
        public string FirstName1 { get; set; }
        public string LastName1 { get; set; }
        public Nullable<System.DateTime> DOB1 { get; set; }
        public string Gender1 { get; set; }
        public string FirstName2 { get; set; }
        public string LastName2 { get; set; }
        public Nullable<System.DateTime> DOB2 { get; set; }
        public string Gender2 { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public Nullable<short> StatusID { get; set; }
        public string UserId { get; set; }
        public string YearMet { get; set; }
        public string ScreenName { get; set; }
        public string Tagline { get; set; }
        public string OurStory { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<bool> enabled { get; set; }
    
        public virtual tblStatus tblStatus { get; set; }
        public virtual ICollection<tblMemberAttributes> tblMemberAttributes { get; set; }
        public virtual ICollection<tblQuestionAnswers> tblQuestionAnswers { get; set; }
        public virtual ICollection<tblMemberMedia> tblMemberMedia { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<Friends> Friends { get; set; }
        public virtual ICollection<Friends> Friends1 { get; set; }
        public virtual ICollection<Favorites> Favorites { get; set; }
        public virtual ICollection<Favorites> Favorites1 { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<DoubleDateMediaUploads> DoubleDateMediaUploads { get; set; }
        public virtual ICollection<DoubleDateRequest> DoubleDateRequest { get; set; }
        public virtual ICollection<DoubleDateRequest> DoubleDateRequest1 { get; set; }
        public virtual ICollection<FavoritePlaces> FavoritePlaces { get; set; }
        public virtual ICollection<MemberInterest> MemberInterest { get; set; }
        public virtual ICollection<tblMemberships> tblMemberships { get; set; }
    }
}
