//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMediaType
    {
        public tblMediaType()
        {
            this.PlaceMedia = new HashSet<PlaceMedia>();
            this.tblMemberMedia = new HashSet<tblMemberMedia>();
        }
    
        public int mediaTypeID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<PlaceMedia> PlaceMedia { get; set; }
        public virtual ICollection<tblMemberMedia> tblMemberMedia { get; set; }
    }
}
