//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMemberMedia
    {
        public int mediaID { get; set; }
        public Nullable<long> memberID { get; set; }
        public Nullable<int> mediaTypeID { get; set; }
        public string path { get; set; }
        public Nullable<bool> primary { get; set; }
    
        public virtual tblMember tblMember { get; set; }
        public virtual tblMediaType tblMediaType { get; set; }
    }
}
