//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMemberAttributes
    {
        public long memberAttributeID { get; set; }
        public long memberID { get; set; }
        public long attributeID { get; set; }
    
        public virtual tblAttributes tblAttributes { get; set; }
        public virtual tblMember tblMember { get; set; }
    }
}
