//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionCategory
    {
        public tblQuestionCategory()
        {
            this.tblQuestions = new HashSet<tblQuestions>();
        }
    
        public short questionCategoryID { get; set; }
        public string questionCategoryName { get; set; }
        public string questionCategoryDescription { get; set; }
    
        public virtual ICollection<tblQuestions> tblQuestions { get; set; }
    }
}
