//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestions
    {
        public tblQuestions()
        {
            this.tblQuestionChoices = new HashSet<tblQuestionChoices>();
            this.tblSubQuestions = new HashSet<tblSubQuestions>();
            this.tblSubQuestions1 = new HashSet<tblSubQuestions>();
        }
    
        public int questionID { get; set; }
        public string questionName { get; set; }
        public string questionFull { get; set; }
        public Nullable<short> questionCategoryID { get; set; }
        public Nullable<short> questionImportance { get; set; }
        public Nullable<bool> multipleAnswersAllowed { get; set; }
        public Nullable<bool> enabled { get; set; }
    
        public virtual tblQuestionCategory tblQuestionCategory { get; set; }
        public virtual ICollection<tblQuestionChoices> tblQuestionChoices { get; set; }
        public virtual ICollection<tblSubQuestions> tblSubQuestions { get; set; }
        public virtual ICollection<tblSubQuestions> tblSubQuestions1 { get; set; }
    }
}
