//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionChoices
    {
        public tblQuestionChoices()
        {
            this.tblQuestionAnswers = new HashSet<tblQuestionAnswers>();
            this.OptInQAnswers = new HashSet<OptInQAnswers>();
        }
    
        public int questionChoiceID { get; set; }
        public string questionChoiceFull { get; set; }
        public Nullable<int> questionID { get; set; }
        public Nullable<int> ordinal { get; set; }
    
        public virtual ICollection<tblQuestionAnswers> tblQuestionAnswers { get; set; }
        public virtual tblQuestions tblQuestions { get; set; }
        public virtual ICollection<OptInQAnswers> OptInQAnswers { get; set; }
    }
}
