//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoupleDating_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStatus
    {
        public tblStatus()
        {
            this.tblMember = new HashSet<tblMember>();
        }
    
        public short statusID { get; set; }
        public string statusDescription { get; set; }
    
        public virtual ICollection<tblMember> tblMember { get; set; }
    }
}
